name: anpr
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - aom=3.12.1
  - blas=1.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.7.3
  - filelock=3.20.0
  - filterpy=1.4.5
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - jinja2=3.1.6
  - jpeg=9f
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran5=11.3.0
  - libglib=2.84.4
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libtiff=4.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.10.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.5
  - numpy-base=2.3.4
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pycparser=2.23
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - pytorch=2.5.1
  - pyyaml=6.0.3
  - readline=8.3
  - requests=2.32.5
  - scipy=1.16.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - anyio==4.11.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - imageio==2.37.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - matplotlib==3.10.7
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - psutil==7.1.3
      - python-dotenv==1.2.1
      - python-telegram-bot==22.5
      - regex==2025.11.3
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - sniffio==1.3.1
      - sympy==1.13.1
      - tifffile==2025.10.16
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - ultralytics==8.3.230
      - ultralytics-thop==2.0.18
